### ISSUE TITLE
No texts in 1.15

### ISSUE THREAD

**Issue by webstoney** [nt1m/livemarks#136]
**Add-on version**
1.15

**Describe the bug**
No strings are shown (neither in bookmarks menu nor in config)

**To Reproduce**
just use German FF (64.0 in my case)

**Expected behavior**
Strings shown

**Comment by nt1m** [comment]
@webstoney My bad, version 1.16 should fix this. Thanks for reporting!

**Comment by evilpie** [comment]
@nt1m So what is the actual fix for this?

**Comment by webstoney** [comment]
@evilpie Update, it is already on AMO.

**Comment by nt1m** [comment]
@evilpie Happy new year :) When I pull from Transifex, it also pulls untranslated languages (German is one of them). When I commit the sync, I don't commit those untranslated files, since they're totally bogus. Unfortunately, when I did  `web-ext build` and uploaded to AMO, I completely forgot I had those bogus files :(

**Comment by evilpie** [comment]
@nt1m happy new year, makes sense!
