### ISSUE TITLE
Visited sites no longer marked as visited.

### ISSUE THREAD

**Issue by JJDLA** [nt1m/livemarks#303]
**Add-on version**
### **Add-on version:3.0

**Describe the bug**
Livemarks no longer marks sites as visited.  This is new behavior since the introduction of FF 84.0b3.

**To Reproduce**
1. Go to Firefox
2. Download 84.ob3

**Expected behavior**
Each visited site should be marked accordingly.**

**Comment by evilpie** [comment]
Can you give an example feed where it doesn't work? Do you have HTTPS-only mode enabled?

**Comment by JJDLA** [comment]
Thanks for the reply.  Here’s some info:


I keep adding sites here and they keep disappearing:


None of my feeds get marked as read after viewing.  Here’s a list of current feeds last saved in August:


This is a list of current NYTimes feeds in Livemarks:


This is a list of current NYTimes feeds in Feebro.  It’s much more up to date:


I’m not clear on your question about HTTPS?  Please help me there.

Again, thanks.
John

**Comment by evilpie** [comment]
Thanks for answering. Sadly it looks like all the feeds you provided were stripped out or something? Have a look at https://github.com/nt1m/livemarks/issues/303#issuecomment-734916491

**Comment by JJDLA** [comment]
Yes, that was me.  Livemarks is still not updating regularly and never shows sites as having been read.
Thanks again

**Comment by evilpie** [comment]
This is not actionable unless we have at least one full URL of a feed that isn't working properly anymore.

**Comment by EverEve** [comment]
Hello, I've noticed this issue, too.

One of the feeds where it happens is the Nightly Blog on the Mozilla website

https://blog.nightly.mozilla.org/feed/

But today, after I gave a "Reload Livemark", the issue seems to be solved.

Dunno if it was something related to a browser regression now corrected, or the interaction between the browser and the addon. 

If you want, I can post another message if the problem arise again.
