### ISSUE TITLE
Dark theme icon problem

### ISSUE THREAD

**Issue by happysurf** [nt1m/livemarks#48]
On dark themes (or in FirefoxColor addon) the icon on address bar is difficult to see, for that I suggest to add an alternative color like orange, good for all themes.

![rss](https://user-images.githubusercontent.com/13637587/47420262-51060400-d77e-11e8-9292-0b3027cbbd45.png)

![rss 3](https://user-images.githubusercontent.com/13637587/47428684-4fdfd180-d794-11e8-982c-91f2d9cb36cb.png)

**Comment by jdittrich** [comment]
A good point – but I wonder how to do this, since it seems currently, the [page action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Page_actions) buttons seem not support reactions to themes, as also [outlined in this stackoverflow ticket](https://stackoverflow.com/questions/48540523/firefox-pick-page-action-icon-for-dark-light-themes#48554293). One could indeed go with the orange icon, but it does not match the rest of the icons well, then.

**Comment by happysurf** [comment]
> 
> 
> A good point – but I wonder how to do this, since it seems currently, the [page action](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Page_actions) buttons seem not support reactions to themes, as also [outlined in this stackoverflow ticket](https://stackoverflow.com/questions/48540523/firefox-pick-page-action-icon-for-dark-light-themes#48554293). One could indeed go with the orange icon, but it does not match the rest of the icons well, then.

Add the orange icon as alternative icon in the extension options, for the users that use dark themes.

**Comment by happysurf** [comment]
In any case the RSS icon is not more a standard feature in Firefox (with same consistence style of all toolbar icons) so it's normal that he has a different style like any other extension.

**Comment by charakterziffer** [comment]
I don’t think the icon of an add-on has to be different than a native feature – quite the contrary I see it as a quality if the add-on integrates seamlessly into the familiar UI and matches the other icons. My suggestion would be to simply use Mozilla’s colouring in the SVG file. So instead of the actual 
`fill="#0c0c0d" fill-opacity="0.6"`
use
`fill="context-fill" fill-opacity="context-fill-opacity"`

That way the icon would be dark in light themes and bright in dark themes. Orange could give problems if somebody uses an orange theme (the same with any non native colour).
